### ISSUE TITLE
Image post on a blog post from Strapi Richtext field?

### ISSUE THREAD

**Issue by sayantannag** [strapi/strapi-meetups#10]
If I want to publish any image for my blog post from the backend Strapi Rich text field then how can I use the same from the media library, where I've already added this? Right now when I choose an uploaded image from the Strapi Rich text image upload button for posting the same in the editor, the image comes with this shared code `![image-name-1110x260](http://localhost:1337/uploads/image-name-1110x260_a4dadcf9e4.jpeg)` in the editor, which does not reflect like image block in the frontend. I need some way it comes with the img tag with the src="" code in it from the admin, so we can view the same like an appropriate image in the frontend as well.

**Comment by vcoisne** [comment]
@sayantannag please ask questions on https://forum.strapi.io/ this repository is for Strapi meetups :)
