### ISSUE TITLE
[New group] Germany, Frankfurt/Rhein-Main

### ISSUE THREAD

**Issue by nkmnz** [strapi/strapi-meetups#3]
# Background Information

- **Name**: Nicolas Katte
- **Company:** edukat.io UG
- **Country, City:** Germany, Frankfurt/Rhein-Main
- **Personal Website or blog:** yourwebsite.com if applicable
- **Twitter:** @yourhandle

# Strapi support needed

- [x] Finding speakers
- [ ] ~~Finding host venues~~ can sponsor venue
- [x] Finding sponsors (can sponsor first meeting though)
- [x] Promoting my events
- [ ] I only need Strapi swag

# Community Guidelines

- [x] I have read & agree to respect Strapi's [code of conduct](https://github.com/strapi/strapi/blob/master/CODE_OF_CONDUCT.md) and [community guidelines](https://github.com/strapi/strapi-meetups/blob/master/guidelines.md)
- [x] I have checked that there is no existing Strapi user group in this city.

**Comment by vcoisne** [comment]
Hello @nkmnz we're live https://www.meetup.com/Strapi-Frankfurt/ closing this issue :)
