### ISSUE TITLE
[New group] Portugal, Lisbon

### ISSUE THREAD

**Issue by matepaiva** [strapi/strapi-meetups#4]
# Background Information

- **Name**: Matheus Paiva
- **Company:** Workmedia
- **Country, City:** Portugal, Lisbon
- **Twitter:** @matepaiva

# Strapi support needed
- [x] Finding speakers
- [x] Finding host venues
- [x] Finding sponsors
- [x] Promoting my events
- [ ] I only need Strapi swag

# Community Guidelines

- [x] I have read & agree to respect Strapi's [code of conduct](https://github.com/strapi/strapi/blob/master/CODE_OF_CONDUCT.md) and [community guidelines](https://github.com/strapi/strapi-meetups/blob/master/guidelines.md)
- [x] I have checked that there is no existing Strapi user group in this city.

**Comment by vcoisne** [comment]
@matepaiva we're live https://www.meetup.com/Strapi-Lisbon/ closing this issue!
